services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "8189:8189"
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./logs:/mediamtx.log
    restart: unless-stopped
    networks:
      - mediamtx-network

networks:
  mediamtx-network:
    driver: bridge